# Fichier : .github/workflows/deploy.yml
name: Deploy Nuxt SSG to GitHub Pages

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: 'pnpm'


      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential
          
      - name: Clear pnpm store
        run: pnpm store prune

      - name: Install dependencies (ignore scripts)
        run: pnpm install --ignore-scripts

      - name: Rebuild native dependencies
        run: pnpm rebuild

      - name: Static generation
        run: pnpm generate
        env:
          NODE_OPTIONS: --openssl-legacy-provider
          NUXT_PUBLIC_SITE_URL: https://${{ github.repository_owner }}.github.io/tncaetfils
          NUXT_APP_BASE_URL: /tncaetfils/
          NUXT_IMAGE_IPX_BASE_URL: /tncaetfils/_ipx

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .output/public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4